/**
* Mapicons
*
* General mapicons.
*
* by Amir Savand
*/

// Functions

SetupMapicons(Float:distance = 1000.0)
{
    // Pay 'N Sprays
    CreateDynamicMapIcon( 1025.05,-1024.23,  32.1, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon(  487.68,-1740.87, 11.13, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon(-1420.73, 2583.37, 55.56, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon(-1904.39,  284.97, 40.75, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon(-2425.91, 1022.33, 50.10, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon( 1975.60, 2162.16, 10.77, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon( 2065.38,-1831.51, 13.25, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon(  -99.55, 1118.36, 19.44, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon(  721.07, -455.94, 16.04, 63, 0, 0, 0, -1, distance);
    CreateDynamicMapIcon( 2393.74, 1493.01, 10.52, 63, 0, 0, 0, -1, distance);

    // Tuning Garages
    CreateDynamicMapIcon( 1039, -1032, 32, 27, 0, 0, 0, -1, distance); // Transfender, Los Santos
    CreateDynamicMapIcon(-1936,   235, 34, 27, 0, 0, 0, -1, distance); // Transfender, San Fierro
    CreateDynamicMapIcon( 2385,  1034, 11, 27, 0, 0, 0, -1, distance); // Transfender, Las Venturas
    CreateDynamicMapIcon( 2646, -2025, 14, 27, 0, 0, 0, -1, distance); // Loco Low Co, Los Santos
    CreateDynamicMapIcon(-2712,   218,  4, 27, 0, 0, 0, -1, distance); // Wheel Arch Angels, San Fierro
}
